version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 10
  method-lines:
    enabled: true
    config:
      threshold: 30
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: false
  identical-code:
    enabled: true
    config:
      threshold: 5

plugins:
  coverage:
    enabled: true
    config:
      coverage_reports:
        - "codeclimate.json"
exclude_patterns:
- "/database/**"
- node_modules/"
- "dist/"
- "package-lock.json"
- ".yml"
- ".husky/*"
- ".husky"
- ".github"
- ".github/*"
