# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  codeclimate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Code Climate | Coverage
        uses: brokeyourbike/codeclimate-action@v0.1.2
        with:
            files: coverage/lcov.info
        env:
          CODECLIMATE_CODE: .
          CC_TEST_REPORTER_ID: f9b4a729716222ef0a20d8782c3a11e6a3e14e2daaf0b86cc9adc5a75eb81abd
          
